Resources:
  EC2SecurityGroupEC2:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for ec2 test
      VpcId:
        !Ref vpcid
      Tags:
        - Key: Name
          Value: !Sub '${org}-${environment}-${vpcStack}-EC2'
        - Key: environment
          Value: !Ref environment
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 30000
          ToPort: 65535
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  EC2SecurityGroupFG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for fargate test
      VpcId:
        !Ref vpcid
      Tags:
        - Key: Name
          Value: !Sub '${org}-${environment}-${vpcStack}-FG'
        - Key: environment
          Value: !Ref environment
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role for IAM Profile
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      RoleName: !Join
        - '-'
        - - 'Meetup-EC2Role'
          - !Ref vpcStack
  LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: !Sub 'amazonlinux2-${vpcStack}'
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !GetAtt IamInstanceProfile.Arn
        UserData:
          'Fn::Base64': !Sub
            - "#!/bin/bash -xe\necho ECS_CLUSTER=${clusterName} >> /etc/ecs/ecs.config\nsudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm\nsudo systemctl enable amazon-ssm-agent"
            - clusterName: !Ref ECSCluster
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: org
                Value: !Ref org
              - Key: environment
                Value: !Ref environment
        InstanceInitiatedShutdownBehavior: stop
        SecurityGroupIds:
          - !Ref EC2SecurityGroupEC2
        EbsOptimized: !Ref EbsOptimized
        DisableApiTermination: False
        ImageId: !Ref amiid
        InstanceType: !Ref InstanceType
        Monitoring: !Ref "AWS::NoValue"
        CreditSpecification: !Ref "AWS::NoValue"
  AutoscalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AutoScalingGroupName: !Sub 'ASG-${org}-${environment}-${vpcStack}'
      Cooldown: !Ref 'AWS::NoValue'
      DesiredCapacity: !Ref DesiredCapacity
      HealthCheckGracePeriod: !Ref HealthCheckGracePeriod
      HealthCheckType: 'EC2'
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !Ref LaunchTemplateVersion
      MaxSize: !Ref MaxSize
      MinSize: !Ref MinSize
      Tags:
        - Key: Name
          Value: !Sub '${org}-${environment}-${vpcStack}'
          PropagateAtLaunch: True
        - Key: environment
          Value: !Ref environment
          PropagateAtLaunch: True
        - Key: org
          Value: !Ref org
          PropagateAtLaunch: True
      TerminationPolicies:
        - OldestInstance
      VPCZoneIdentifier:
            - !Ref subnet1Private
            - !Ref subnet2Private
            - !Ref subnet3Private
  ElasticLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      LoadBalancerAttributes:
        - Key: routing.http2.enabled
          Value: "true"
        - Key: idle_timeout.timeout_seconds
          Value: "600"
        - Key: deletion_protection.enabled
          Value: "false"
      Name: !Sub '${environment}-${vpcStack}-loadbalancer'
      Scheme: !Ref loadbalancerscheme
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - !Ref subnet1Public
        - !Ref subnet2Public
        - !Ref subnet3Public
      Tags:
        - Key: org
          Value: !Ref org
        - Key: environment
          Value:  !Ref environment
      Type: application
      IpAddressType: ipv4
  ALBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow http and https into alb
      VpcId:
        !Ref vpcid
      Tags:
        - Key: Name
          Value: !Sub '${environment}-${vpcStack}-ALBSG'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  TargetGroupEC2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: "200"
      Name: !Join
        - '-'
        - - !Sub '${environment}TargetGroup80EC2'
          - !Ref vpcStack
      Port: 80
      Protocol: HTTP
      Tags:
        - Key: org
          Value: !Ref org
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "30"
      TargetType: instance
      UnhealthyThresholdCount: 2
      VpcId:
        !Ref vpcid
  TargetGroupFARGATE:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: "200"
      Name: !Join
        - '-'
        - - !Sub '${environment}TargetGroup80FARGATE'
          - !Ref vpcStack
      Port: 80
      Protocol: HTTP
      Tags:
        - Key: org
          Value: !Ref org
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "30"
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId:
        !Ref vpcid
  Listener80:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - FixedResponseConfig:
            ContentType: text/plain
            StatusCode: "200"
            MessageBody: "You cannot get there from here"
          Type: fixed-response
      LoadBalancerArn: !Ref ElasticLoadBalancer
      Port: 80
      Protocol: HTTP
  ListenerRuleFG:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
          ListenerArn: !Ref Listener80
          Priority: 2
          Conditions:
              - Field: path-pattern
                Values:
                  - '/FG*'
          Actions:
              - TargetGroupArn: !Ref TargetGroupFARGATE
                Type: forward
  ListenerRuleEC2:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
          ListenerArn: !Ref Listener80
          Priority: 3
          Conditions:
              - Field: path-pattern
                Values:
                  - '/EC2*'
          Actions:
              - TargetGroupArn: !Ref TargetGroupEC2
                Type: forward
Parameters:
  ECSCluster:
    Type: String
    Description:  the name of the cluster for userdata
  org:
    Type: 'String'
    Default: cloudbutton
    Description: organization
  environment:
    Type: String
    Default: prod
    Description: environment
  level:
    Type: String
    Default: benchmark
    Description: Name of level used for naming convention
  InstanceType:
    Type: 'String'
    Default: t2.micro
    Description: instance size
  amiid:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
    Description: ami id
  EbsOptimized:
    Type: String
    Default: false
    Description:  Ebs Optimized?
  vpcStack:
    Type: String
    Default: bench2
    Description:  which cf to link to
  LaunchTemplateVersion:
    Type: String
    Default: 1
    Description: Launch Template Version
  HealthCheckGracePeriod:
    Type: String
    Default: 900
    Description:  period after which to start health monitoring
  MinSize:
    Type: String
    Default: 1
    Description:  Minimum size of asg
  MaxSize:
    Type: String
    Default: 1
    Description:  Maximum size of asg
  DesiredCapacity:
    Type: String
    Default: 1
    Description: Desired Capacity size of asg
  loadbalancerscheme:
    Type: String
    Default: internet-facing
    Description: internet-facing or internal
  vpcid:
    Type: String
    Default: None
  subnet1Public:
    Type: String
    Default: None
  subnet2Public:
    Type: String
    Default: None
  subnet3Public:
    Type: String
    Default: None
  subnet1Private:
    Type: String
    Default: None
  subnet2Private:
    Type: String
    Default: None
  subnet3Private:
    Type: String
    Default: None
Outputs:
    ElasticLoadBalancerDNS:
      Description: Load balancer dns
      Value: !GetAtt ElasticLoadBalancer.DNSName
      Export:
        Name: !Join [ ":", [ !Ref "AWS::StackName", ElasticLoadBalancerDNS ] ]
        Value: !GetAtt ElasticLoadBalancer.DNSName
    FargateLink:
      Description: link for fargate endpoint
      Value: !Sub '${ElasticLoadBalancer.DNSName}/FG'
    EC2Link:
      Description: link for fargate endpoint
      Value: !Sub '${ElasticLoadBalancer.DNSName}/EC2'
    TargetGroupArnEC2:
      Description: targetgroup arn
      Value: !Ref TargetGroupEC2
      Export:
        Name: !Sub '${org}-${environment}-${level}:targetgroupec2'
        Value: !Ref TargetGroupEC2
    TargetGroupArnFARGATE:
      Description: targetgroup arn
      Value: !Ref TargetGroupFARGATE
      Export:
        Name: !Sub '${org}-${environment}-${level}:targetgroupfargate'
        Value: !Ref TargetGroupFARGATE
    SecurityGroupEC2:
      Description: security group for containers
      Value: !Ref EC2SecurityGroupEC2
      Export:
        Name: !Sub '${org}-${environment}-${level}:securitygroupec2'
        Value: !Ref EC2SecurityGroupEC2
    SecurityGroupFG:
      Description: security group for containers
      Value: !Ref EC2SecurityGroupFG
      Export:
        Name: !Sub '${org}-${environment}-${level}:securitygroupfg'
        Value: !Ref EC2SecurityGroupFG


